name: Auto commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "DamianReeves/write-file-action@master"
        with:
          path: dummy_file
          write-mode: overwrite
          contents: Overwritten by Github Actions - ${date}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "auto-commit"
          create_branch: true
          commit_message: "auto commit"
          commit_options: '--allow-empty'
          add_options: '-A'
          push_options: '--force'
          
          
